# Python字符串方法列表
# 方法	描述说明
# capitalize()	将字符串的首字母大写
# casefold()	将整个字符串转换为小写（更彻底）
# center()	返回居中对齐的字符串
# count()	返回指定字符或子串出现次数
# encode()	返回字符串编码后的字节串
# endswith()	检查字符串是否以指定值结尾
# expandtabs()	设置字符串的Tab制表符大小
# find()	搜索指定内容并返回位置（未找到返回-1）
# format()	格式化字符串
# format_map()	使用映射关系格式化字符串
# index()	搜索指定内容的位置（未找到会报错）
# isalnum()	检测所有字符是否为字母或数字
# isalpha()	检测所有字符是否都是字母
# isascii()	检测所有字符是否为ASCII字符
# isdecimal()	检测所有字符是否为十进制数字
# isdigit()	检测所有字符是否都是数字
# isidentifier()	检测字符串是否为有效的标识符
# islower()	检测所有字符是否都是小写字母
# isnumeric()	检测所有字符是否为数字字符
# isprintable()	检测所有字符是否为可打印字符
# isspace()	检测所有字符是否为空白字符
# istitle()	检测字符串是否符合标题格式（首字母大写）
# isupper()	检测所有字符是否都是大写字母
# join()	将序列中的元素连接成字符串
# ljust()	返回左对齐的字符串
# lower()	将字符串转换为小写
# lstrip()	删除字符串左侧空白字符
# maketrans()	创建字符映射转换表
# partition()	将字符串分为三部分（前、分隔符、后）
# replace()	用指定内容替换原内容
# rfind()	从右侧搜索指定内容并返回位置（未找到返回-1）
# rindex()	从右侧搜索指定内容位置（未找到会报错）
# rjust()	返回右对齐的字符串
# rpartition()	从右侧将字符串分为三部分
# rsplit()	从右侧分割字符串并返回列表
# rstrip()	删除字符串右侧空白字符
# split()	分割字符串为列表
# splitlines()	按行分割字符串
# startswith()	检测是否以指定字符开头
# strip()	删除字符串两端空白字符
# swapcase()	大小写互换
# title()	将每个单词首字母大写
# translate()	替换指定字符（需配合maketrans()）
# upper()	将字符串转换为大写
# zfill()	在字符串前填充0达到指定长度